export const AGENT_ROLES = Object.freeze({
  LATTICE_PM: "LATTICE_PM",
  PLANNER: "PLANNER",
  CODE_MAPPER: "CODE_MAPPER",
  GRAPHIFY: "GRAPHIFY",
  IMPLEMENTER: "IMPLEMENTER",
  CORRECTNESS_REVIEWER: "CORRECTNESS_REVIEWER",
  SECURITY_REVIEWER: "SECURITY_REVIEWER",
  ARCHITECTURE_REVIEWER: "ARCHITECTURE_REVIEWER",
  INTEGRATOR: "INTEGRATOR",
});

export const ACTIONS = Object.freeze({
  READ_REPOSITORY: "READ_REPOSITORY",
  SUBMIT_PLAN: "SUBMIT_PLAN",
  PLAN_TASK: "PLAN_TASK",
  MAP_CODE: "MAP_CODE",
  WRITE_PRODUCT_CODE: "WRITE_PRODUCT_CODE",
  RUN_TESTS: "RUN_TESTS",
  REVIEW_CORRECTNESS: "REVIEW_CORRECTNESS",
  REVIEW_SECURITY: "REVIEW_SECURITY",
  REVIEW_ARCHITECTURE: "REVIEW_ARCHITECTURE",
  PREPARE_WORKTREE: "PREPARE_WORKTREE",
  INTEGRATE_GIT: "INTEGRATE_GIT",
  STOP_RUNTIME: "STOP_RUNTIME",
  RESOLVE_MERGE_CONFLICT: "RESOLVE_MERGE_CONFLICT",
  CALL_REAL_MODEL: "CALL_REAL_MODEL",
  NETWORK_ACCESS: "NETWORK_ACCESS",
  DEPLOY_PRODUCTION: "DEPLOY_PRODUCTION",
  PURCHASE_SERVICE: "PURCHASE_SERVICE",
  MANAGE_CREDENTIALS: "MANAGE_CREDENTIALS",
  PUBLIC_PUBLISH: "PUBLIC_PUBLISH",
  PERMANENT_DELETE: "PERMANENT_DELETE",
  ACCESS_PLAYMATE: "ACCESS_PLAYMATE",
  DISABLE_SECURITY: "DISABLE_SECURITY",
});

const read = ACTIONS.READ_REPOSITORY;

export const ROLE_ACTIONS = Object.freeze({
  [AGENT_ROLES.LATTICE_PM]: Object.freeze([
    read,
    ACTIONS.SUBMIT_PLAN,
    ACTIONS.STOP_RUNTIME,
  ]),
  [AGENT_ROLES.PLANNER]: Object.freeze([read, ACTIONS.PLAN_TASK]),
  [AGENT_ROLES.CODE_MAPPER]: Object.freeze([read, ACTIONS.MAP_CODE]),
  [AGENT_ROLES.GRAPHIFY]: Object.freeze([read, ACTIONS.MAP_CODE]),
  [AGENT_ROLES.IMPLEMENTER]: Object.freeze([
    read,
    ACTIONS.WRITE_PRODUCT_CODE,
    ACTIONS.RUN_TESTS,
  ]),
  [AGENT_ROLES.CORRECTNESS_REVIEWER]: Object.freeze([
    read,
    ACTIONS.REVIEW_CORRECTNESS,
  ]),
  [AGENT_ROLES.SECURITY_REVIEWER]: Object.freeze([
    read,
    ACTIONS.REVIEW_SECURITY,
  ]),
  [AGENT_ROLES.ARCHITECTURE_REVIEWER]: Object.freeze([
    read,
    ACTIONS.REVIEW_ARCHITECTURE,
  ]),
  [AGENT_ROLES.INTEGRATOR]: Object.freeze([
    read,
    ACTIONS.PREPARE_WORKTREE,
    ACTIONS.INTEGRATE_GIT,
  ]),
});

export const PHASE1_PROTECTED_ACTIONS = new Set([
  ACTIONS.RESOLVE_MERGE_CONFLICT,
  ACTIONS.CALL_REAL_MODEL,
  ACTIONS.NETWORK_ACCESS,
  ACTIONS.DEPLOY_PRODUCTION,
  ACTIONS.PURCHASE_SERVICE,
  ACTIONS.MANAGE_CREDENTIALS,
  ACTIONS.PUBLIC_PUBLISH,
  ACTIONS.PERMANENT_DELETE,
  ACTIONS.ACCESS_PLAYMATE,
  ACTIONS.DISABLE_SECURITY,
]);

